login: nherbaut
pwd: azerty1A;
api-backend: https://api.grid5000.fr/
ssh_key_file_public: /home/nherbaut/.ssh/id_rsa.pub
ssh_key_file_private: /home/nherbaut/.ssh/id_rsa
g5k_ssh_key_file_private: /home/nherbaut/.ssh/g5k
g5k_ssh_key_file_public: /home/nherbaut/.ssh/g5k.pub
mailto: nicolas.herbaut@gmail.com
grid5k_ProxyCommand_domain_alias: g5k
environment: debian9-x64-base
default_site: nancy
default_queue: default
salt_host_control_iface: eth0
salt_host_data_iface: eth0
salt_minion_template: ./minion.tpl
salt_master_template: ./master.tpl
salt_states_repo_url: https://gricad-gitlab.univ-grenoble-alpes.fr/herbautn/antidote-stack
salt_states_repo_branch: master
salt_state_dest_folder: /srv
salt_master_precommands:
  - apt-get update
  - apt-get install git python-pip --yes
  - pip install docker netifaces
salt_master_postcommands:
  - salt-run state.orchestrate orch
salt_minion_precommands:
  - apt-get update
  - apt-get install git python-pip --yes
  - pip install docker netifaces
salt_minion_postcommands: []
salt_master_file_managed:
  - src: ./placement.sls
    dst: /srv/pillar/placement.sls
  - src: ./antidote.sls
    dst: /srv/pillar/antidote.sls

